# Generated by Django 3.2.5 on 2022-08-11 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]