# Generated by Django 3.2.5 on 2022-08-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='creator',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notes',
            name='last_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]