# Generated by Django 3.2.5 on 2022-08-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20220808_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='image',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='tags',
        ),
        migrations.AddField(
            model_name='notes',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
