# Generated by Django 3.2.5 on 2022-08-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20220809_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='votes',
        ),
    ]
