# Generated by Django 3.2.5 on 2022-08-16 13:26

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='write',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
