# Generated by Django 3.2.5 on 2022-08-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_quillpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuillPost',
        ),
        migrations.AlterField(
            model_name='notes',
            name='write',
            field=models.TextField(),
        ),
    ]
